---
- name: Install python kubernetes packages on nodes
  hosts: all
  become: true
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
    - name: Install Kubernetes python package
      pip:
        name: kubernetes
