---
- name: Install python kubernetes packages on nodes
  hosts: workers
  become: true
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
    - name: Install Kubernetes python package
      ansible.builtin.pip:
        name: kubernetes
