---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - add_host:
        name: "{{ item }}"
        groups: limited_selection
      loop: "{{ (groups['all'] | shuffle)[0:1] }}"

- hosts: limited_selection
  gather_facts: no
  tasks:
    - reboot:
