apiVersion: v1
kind: Service
metadata:
  name: speedtester-service
spec:
  selector:
    run: speedtester
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080
