---
- name: "nautobot lab locations"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    nautobot_url: "{{ lookup('env', 'NAUTOBOT_URL') }}"
    nautobot_token: "{{ lookup('env', 'NAUTOBOT_TOKEN') }}"

  tasks:
    - name: "add locations"
      networktocode.nautobot.location:
        url: "{{ nautobot_url }}"
        token: "{{ nautobot_token }}"
        name: "{{ location['name'] }}"
        location_type: "{{ location['location_type'] }}"
        parent_location: "{{ location['parent'] | default(omit) }}"
        status: "{{ location['status'] }}"
        state: present
      loop_control:
        loop_var: location
      loop:
        - name: "Lab"
          location_type: "Site"
          status: "Active"
