---
- name: "nautobot lab vlans"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    nautobot_url: "{{ lookup('env', 'NAUTOBOT_URL') }}"
    nautobot_token: "{{ lookup('env', 'NAUTOBOT_TOKEN') }}"

  tasks:
    - name: "add vlans"
      networktocode.nautobot.vlan:
        url: "{{ nautobot_url }}"
        token: "{{ nautobot_token }}"
        name: "{{ item.name }}"
        vid: "{{ item.vlanid }}"
        status: "{{ item.status }}"
        state: present
      loop:
        - { name: "Lab LAN", vlanid: 1, status: Active }
