---
- name: "nautobot lab prefixes"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    nautobot_url: "{{ lookup('env', 'NAUTOBOT_URL') }}"
    nautobot_token: "{{ lookup('env', 'NAUTOBOT_TOKEN') }}"

  tasks:
    - name: "add prefixes"
      networktocode.nautobot.prefix:
        url: "{{ nautobot_url }}"
        token: "{{ nautobot_token }}"
        prefix: "192.168.99.0/24"
        vlan:
          name: Lab LAN
        type: Network
        status: Active
        state: present
