---
- hosts: server
  become: true
  vars:
    http_host: "hashtopolis"
  tasks:
    - name: Remove install directory
      file:
        path: "/var/www/{{ http_host }}/install"
        state: "absent"
    - name: Remove php info
      file:
        path: "/var/www/{{ http_host }}/info.php"
        state: "absent"
