---
- hosts: all
  name: application_fleet.yml
  become: true
  gather_facts: true
  vars_files:
    - application.yml
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: true
    - name: Install PHP and extensions
      apt:
        name:
          - php
          - php-fpm # For FastCGI Process Manager
        state: present
    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: true
    - name: Get list of services
      service_facts:
    - name: get the php-fwm version
      set_fact:
        php_fpm_version: "{{ item }}"
      when:
        - ansible_facts.services[item].name | regex_search("^php.+fpm$")
      with_items: "{{ ansible_facts.services }}"
    - name: Start and enable PHP-FPM
      service:
        name: "{{ php_fpm_version }}"
        state: started
        enabled: true
    - name: Create a phpinfo page
      blockinfile:
        path: /var/www/html/index.php
        block: |
          <?php phpinfo(); ?>
        create: true
        marker: ""
    - name: Create application conf file
      template:
        src: ./app-conf.j2
        dest: "/etc/nginx/sites-available/{{ application.Name }}.conf"
        mode: "755"
    - name: Activate Nginx site by creating symlink
      file:
        src: "/etc/nginx/sites-available/{{ application.Name }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ application.Name }}.conf"
        state: link
    - name: Deactivate default site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
