---
- hosts: localhost  # Run on the local machine
  connection: local
  gather_facts: false
  vars_files:
    - variables.yml
  vars:
    vm_name: my_vm

  tasks:
  - name: Shut down VM with this name
    command: "{{ Global.vboxmanage_path }} controlvm {{ vm_name }} acpipowerbutton"
  - name: Pause 1 minute
    pause:
      minutes: 1
  - name: Remove any old VM with this name
    command: "{{ Global.vboxmanage_path }} unregistervm --delete {{ vm_name }}"
