---
- name: Install Virtualbox
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Add Oracle apt key
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present
    - name: Add Virtualbox repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
        state: present
    - name: Install Virtualbox
      apt:
        pkg:
          - virtualbox
        state: present
        update_cache: true
    - name: Ensure vboxdrv kernel module is loaded (optional)
      modprobe:
        name: vboxdrv
        state: present
