---
- hosts: localhost  # Run actions on the local machine
  name: start_fleet.yml
  connection: local
  gather_facts: false
  vars_files:
    - variables.yml
    - servers.yml
  tasks:
    - name: Start VM
      command: "{{ Global.vboxmanage_path }} startvm {{ item.Name }}"
      ignore_errors: true
      when: item.Deploy
      loop: "{{ Server_List }}"
