---
- hosts: clients
  become: true
  become_user: root
  tasks:
    - name: Read FAH client from config.xml
      shell: cat /etc/fahclient/config.xml
      changed_when: false
      register: configuration
    - name: Dump configuration
      debug:
        var: configuration.stdout_lines
