---
- name: Check temperature
  hosts: clients
  remote_user: ansible
  become: true
  tasks:
    - name: Gather CPU temperature
      shell: "sensors | grep 'Package id 0:' | cut -c17-20"
      register: temp
      changed_when: false
    - name: Check CPU temperature
      fail:
        msg: "{{ temp.stdout }}"
      when: (temp.stdout | int > 80)
