---
- hosts: server
  become: true
  become_user: root
  tasks:
    - name: Stop and disable services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
        - apache2
        - mysql
    - name: Remove packages
      apt:
        name:
          - apache2
          - mysql
          - python3-pymysql
          - php
          - php-pear
          - php-mysql
          - libapache2-mod-php
        state: absent
        autoclean: true
        purge: true
    - name: Remove directory
      file:
        state: absent
        path: /var/www/hashtopolis
- hosts: agents
  become: true
  become_user: root
  tasks:
    - name: Stop and disable services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
        - hashtopolis-agent
    - name: Remove packages
      apt:
        name:
          - git
          - zip
          - curl
          - hashcat
          - python3-psutil
          - python3-requests
          - pciutils
        state: absent
        autoclean: true
        purge: true
