---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Stop and disable FAHClient.service
      ansible.builtin.service:
        name: FAHClient.service
        state: stopped
        enabled: false
    - name: Wait for termination of all FaH client processes
      wait_for:
        path: /var/run/fahclient.pid
        state: absent
    - name: Remove fahclient package
      apt:
        name: fahclient
        state: absent
        autoclean: true
        purge: true
    - name: Reboot
      reboot:
