---
- name: Create Branch 1 policy
  hosts: check_point
  connection: httpapi
  collections:
    - check_point.mgmt
  # include_vars: vars.yml # introduced in Ansible 2.11
  tasks:
    - name: add a policy package
      check_point.mgmt.cp_mgmt_package:
        access: true
        color: forest green
        comments: Access policy for Lab
        name: Lab_Policy
        state: present
        threat_prevention: false
    - name: modify cleanup rule
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: Cleanup rule
        action: Accept
        enabled: true
        track:
          type: Log
        comments: Turn cleanup rule into allow all rule
        state: present
    - name: create cleanup section
      check_point.mgmt.cp_mgmt_access_section:
        layer: Lab_Policy Network
        name: Cleanup section
        relative_position:
          above: Cleanup rule
        state: present
    - name: create gateways access section
      check_point.mgmt.cp_mgmt_access_section:
        layer: Lab_Policy Network
        name: Gateways access
        position: top
        state: present
    - name: create stealth section
      check_point.mgmt.cp_mgmt_access_section:
        layer: Lab_Policy Network
        name: Stealth rules
        relative_position:
          below: Gateways access
        state: present
    - name: create DMZ section
      check_point.mgmt.cp_mgmt_access_section:
        layer: Lab_Policy Network
        name: DMZ
        relative_position:
          below: Stealth rule
    - name: create core services section
      check_point.mgmt.cp_mgmt_access_section:
        layer: Lab_Policy Network
        name: Core Services
        relative_position:
          below: DMZ      
    - name: create general Internet access section
      check_point.mgmt.cp_mgmt_access_section:
        layer: Lab_Policy Network
        name: General Internet access
        relative_position:
          below: Core Services
    - name: create noise suppression section
      check_point.mgmt.cp_mgmt_access_section:
        layer: Lab_Policy Network
        name: Noise suppressio
        relative_position:
          below: General Internet access
    - name: add gateways access rule
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: Manage gateways
        relative_position:
          below: Gateways access
        source:
          - Manager
        destination:
          - firewall1
        service:
        - https
        - echo-reply
        - ssh_version_2
        action: Accept
        comments: Allow manage gateways
        track:
          type: Log
        state: present
    - name: add a stealth rule
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: Stealth rule
        relative_position:
          below: Stealth rules
        source:
          - Any
        destination:
          - firewall1
        service:
        - Any
        action: Drop
        comments: Protect gateways
        track:
          type: Log
        state: present
    - name: add core services ntp allowed
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: NTP allowed
        relative_position:
          below: Core Services
        source:
          - branch1_lan
          - branch1_dmz
          - management_192.168.41.0/24
        destination:
          - .time.windows.com
          - .ntp.checkpoint.com
          - .ntp2.checkpoint.com
        service:
        - ntp
        action: Accept
        comments: Approved ntp
        track:
          type: Log
        state: present
    - name: add core services dns allowed
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: DNS allowed
        relative_position:
          below: NTP allowed
        source:
          - dc-1
          - sms
        destination:
          - google_dns_8.8.8.8
          - google_dns_8.8.4.4
          - quad9_dns_9.9.9.9
        service:
        - dns
        action: Accept
        comments: Approved dns
        track:
          type: Log
        state: present
    - name: add DMZ rule internal access to web apps
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: Internal web access to DMZ
        relative_position:
          below: DMZ
        source:
          - management_192.168.41.0/24
          - branch1_lan
        destination:
          - branch1_dmz
        service:
        - http
        - https
        - echo-request
        action: Accept
        comments: Web access to DMZ apps
        track:
          type: Log
        state: present
    - name: add DMZ rule access to domain controller
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: DMZ to Domain Controller
        relative_position:
          below: Internal web access to DMZ
        source:
          - dmz-iis
        destination:
          - dc-1
        service:
        - active_directory_ports
        action: Accept
        comments: DMZ to Domain Controller
        track:
          type: Log
        state: present
    - name: add DMZ rule access to internal DNS
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: DMZ DNS
        relative_position:
          below: DMZ to Domain Controller
        source:
          - branch1_dmz
        destination:
          - dc-1
        service:
        - dns
        - echo-request
        action: Accept
        comments: DMZ to Domain Controller DNS
        track:
          type: Log
        state: present
    - name: add DMZ rule access to SQL server
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: DMZ SQL
        relative_position:
          below: DMZ DNS
        source:
          - dmz-iis
        destination:
          - sql-1
        service:
        - MS-SQL-Server
        action: Accept
        comments: DMZ Web server to SQL server
        track:
          type: Log
        state: present
    - name: add DMZ rule inbound web traffic
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: DMZ Inbound Web
        relative_position:
          below: DMZ SQL
        source:
          - All_Internet
        destination:
          - dmz-iis
          - dmz-apache
        service:
        - http
        - https
        action: Accept
        comments: DMZ Web server to SQL server
        track:
          type: Log
        state: present
    - name: add Internet access rule
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: Web access
        relative_position:
          below: General Internet access
        source:
          - management_192.168.41.0/24
          - branch1_lan
        destination:
          - All_Internet
        service:
        - http
        - https
        - echo-request
        action: Accept
        comments: Protect gateways
        track:
          type: Log
        state: present
    - name: add noise suppression rule netbios
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: netbios broadcasts
        relative_position:
          below: Noise suppression
        source:
          - management_192.168.41.0/24
          - branch1_lan
        destination:
          - broadcast_192.167.41.255
          - broadcast_10.0.1.255
        service:
        - nbname
        - nbdatagram
        action: Drop
        comments: Do not log netbios broadcasts
        track:
          type: None
        state: present
    - name: add noise suppression rule multicast
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: netbios broadcasts
        relative_position:
          below: netbios broadcasts
        source:
          - management_192.168.41.0/24
          - branch1_lan
        destination:
          - multicast_239.255.255.250
        service:
        - udp_1900
        action: Drop
        comments: Do not log LLMNR and SSDP multicast drops
        track:
          type: None
        state: present
    - name: create NAT rule section No-NAT
      check_point.mgmt.cp_mgmt_nat_section:
        package: Lab_Policy
        name: No-NAT
        position: top
        state: present
    - name: add DMZ No-NAT LAN rule
      check_point.mgmt.cp_mgmt_nat_rule:
        package: Lab_Policy
        name: LAN No-NAT
        comments: No-NAT LAN to DMZ
        original_source: branch1_lan
        original_destination: branch1_dmz
        relative_position:
          below: No-NAT
        state: present
    - name: add DMZ No-NAT Mgmt rule
      check_point.mgmt.cp_mgmt_nat_rule:
        package: Lab_Policy
        name: Management No-NAT
        comments: No-NAT LAN to DMZ
        original_source: management_192.168.41.0/24
        original_destination: branch1_dmz
        relative_position:
          below: LAN No-NAT
        state: present
    - name: publish changes
      check_point.mgmt.cp_mgmt_publish:
