---
- name: Create policy
  hosts: check_point
  connection: httpapi
  # include_vars: vars.yml # introduced in Ansible 2.11
  tasks:
    - name: add a package
      cp_mgmt_package:
        access: true
        color: forest green
        comments: Access policy for Lab
        name: Lab_Policy
        state: present
        threat_prevention: false
    - name: add a rule
      cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: Rule 1
        position: top
        source:
          - branch1_lan
        destination:
          - Any
        service:
        - http
        - https
        - echo-reply
        - dns
        action: Accept
        comments: Allow web traffic
        track:
          type: Log
        state: present
    - name: modify cleanup rule
      cp_mgmt_access_rule:
        layer: Lab_Policy Network
        name: Cleanup rule
        action: Accept
        enabled: true
        track:
          type: Log
        comments: Turn cleanup rule into allow all rule
        state: present
