---
- name: Configure DMZ Apache web server
  hosts: 192.168.31.11
  become: true
  vars:
    servername: dmz-apache
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ servername }}"
    - name: Install Apache
      apt:
        name: apache2
        update_cache: true
        state: present
    - name: Start Apache service
      service:
        name: apache2
        state: started   
    - name: Install PHP
      apt:
        name: php
        state: present
    - name: Generate SSL certificate
      command: certbot certonly --webroot -w /var/www/html -d {{ servername }}
      register: certbot_result
    - name: Check certificate generation
      debug:
        msg: "Certificate generated: {{ certbot_result.changed }}"
    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
    - name: Copy certificate
      copy:
        src: /etc/letsencrypt/live/{{ servername }}/fullchain.pem
        dest: /etc/apache2/ssl/{{ servername }}.crt
        mode: 0600
    - name: Copy key
      copy:
        src: /etc/letsencrypt/live/{{ servername }}/privkey.pem
        dest: /etc/apache2/ssl/{{ servername }}.key
        mode: 0600
    - name: Create SSL configuration file
      template:
        src: https.conf.j2
        dest: /etc/apache2/sites-enabled/{{ servername }}.conf
    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
