---
- name: Create management objects
  hosts: check_point
  connection: httpapi
  # include_vars: vars.yml # introduced in Ansible 2.11
  tasks:
    - name: management workstation
      cp_mgmt_host:
        name: Manager
        ipv4_address: 192.168.41.100
        color: dark green
        comments: management workstation
        state: present
    - name: Management network
      cp_mgmt_network:
        name: management_192.168.41.0/24
        subnet: 192.168.41.0
        mask_length: 24
        color: crete blue
        comments: management network
        state: present
    - name: management network broadcast address
      cp_mgmt_host:
        name: broadcast_192.168.41.255
        ipv4_address: 192.168.41.255
        color: slate blue
        comments: management network broadcast address
        state: present
    - name: dns 8.8.8.8
      cp_mgmt_host:
        name: google_dns_8.8.8.8
        ipv4_address: 8.8.8.8
        color: dark orange
        comments: Google DNS server 8.8.8.8
        state: present
    - name: dns 8.8.4.4
      cp_mgmt_host:
        name: google_dns_8.8.4.4
        ipv4_address: 8.8.4.4
        color: dark orange
        comments: Google DNS server 8.8.4.4
        state: present
    - name: dns quad9
      cp_mgmt_host:
        name: quad9_dns_9.9.9.9
        ipv4_address: 9.9.9.9
        color: dark orange
        comments: Quad9 DNS server 9.9.9.9
        state: present
    - name: dns cloudflare 1.1.1.1
      cp_mgmt_host:
        name: cloudflare_dns_1.1.1.1
        ipv4_address: 1.1.1.1
        color: dark orange
        comments: cloudflare dns 1.1.1.1
        state: present
    - name: publish changes
      cp_mgmt_publish:
