---
- hosts: master
  become: true
  # gather_facts: false
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: sql
  become: true
  tasks:
    - name: TCP port 6443 on master is reachable from worker
      wait_for: "host={{ 'MASTERIP' }} port=6443 timeout=1"

    - name: Join cluster
      shell: "{{ hostvars['MASTERIP'].join_command }} >> node_joined.log"
      args:
        chdir: /home/ansible
        creates: node_joined.log
